const KEY='mylife-prototype-items';
let items=[];let confirmAction=null;
try{const stored=JSON.parse(localStorage.getItem(KEY)||'[]');items=Array.isArray(stored)?stored.filter(i=>i&&i.id&&i.name&&i.date):[]}catch{try{localStorage.removeItem(KEY)}catch{}}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>globalThis.crypto?.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function localDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function dateAfter(days){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+days);return localDate(d)}
const samples={roadtax:{icon:'🚗',name:'Road tax — Ativa',category:'Vehicle',days:45,amount:90,repeat:'yearly'},internet:{icon:'🛜',name:'Home internet bill',category:'Bills',days:12,amount:129,repeat:'monthly'},warranty:{icon:'💻',name:'Laptop warranty',category:'Warranty',days:180,amount:0,repeat:'none'}};
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='timeline'||id==='upcoming')render()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(items));return true}catch{openConfirm('Storage unavailable','This browser could not save your changes.','OK',()=>{});return false}}
function diff(date){const now=new Date();now.setHours(12,0,0,0);return Math.round((new Date(date+'T12:00:00')-now)/86400000)}
function money(n){return 'RM'+Number(n||0).toLocaleString('en-MY',{maximumFractionDigits:2})}
function escapeHtml(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
function render(){const box=$('#items');box.innerHTML=items.length?'':'<div class="empty">Nothing tracked yet. Snap a document or add something manually.</div>';items.forEach((i,index)=>{const d=diff(i.date);box.innerHTML+=`<div class="item" data-id="${escapeHtml(i.id)}"><div class="icon">${i.icon||'📌'}</div><button class="item-main edit-item" data-id="${escapeHtml(i.id)}"><strong>${escapeHtml(i.name)}</strong><small>${escapeHtml(i.category)} · ${new Date(i.date+'T12:00:00').toLocaleDateString('en-MY',{day:'numeric',month:'short',year:'numeric'})}${i.amount?' · '+money(i.amount):''} · Edit</small></button><div class="item-side"><span class="days ${d<=14?'urgent':''}">${d<0?'OVERDUE':d===0?'TODAY':d+' DAYS'}</span><span class="move"><button class="move-btn" data-dir="up" data-index="${index}" aria-label="Move ${escapeHtml(i.name)} up" ${index===0?'disabled':''}>↑</button><button class="move-btn" data-dir="down" data-index="${index}" aria-label="Move ${escapeHtml(i.name)} down" ${index===items.length-1?'disabled':''}>↓</button></span></div></div>`});
$$('.edit-item').forEach(b=>b.onclick=()=>editItem(b.dataset.id));$$('.move-btn').forEach(b=>b.onclick=()=>moveItem(Number(b.dataset.index),b.dataset.dir));
const next=items.filter(i=>{const d=diff(i.date);return d>=0&&d<=90});$('#count').textContent=`${next.length} item${next.length===1?'':'s'}`;$('#cost').textContent=`${money(next.reduce((s,i)=>s+Number(i.amount||0),0))} scheduled`;
const alerts=$('#alerts');const due=items.filter(i=>diff(i.date)<=Number(i.reminder||30)).sort((a,b)=>a.date.localeCompare(b.date));alerts.innerHTML=due.length?'':'<div class="empty">No reminders need your attention.</div>';due.forEach(i=>{const d=diff(i.date);alerts.innerHTML+=`<div class="alert"><strong>${d<0?'⚠️ Overdue':d===0?'🔔 Due today':'🔔 '+d+' days left'} — ${escapeHtml(i.name)}</strong><span>${escapeHtml(i.category)}${i.amount?' · '+money(i.amount):''}</span></div>`})}
function moveItem(index,dir){const target=dir==='up'?index-1:index+1;if(target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];save();render()}
function clearForm(){const f=$('#itemForm');f.reset();$('#editId').value='';$('#formTitle').textContent='Add manually';$('#deleteBtn').classList.add('hidden')}
function editItem(id){const i=items.find(x=>x.id===id);if(!i)return;$('#editId').value=i.id;$('#name').value=i.name;$('#category').value=i.category;$('#date').value=i.date;$('#amount').value=i.amount||'';$('#repeat').value=i.repeat||'none';$('#reminder').value=String(i.reminder||30);$('#formTitle').textContent='Edit tracked item';$('#deleteBtn').classList.remove('hidden');show('add')}
function openConfirm(title,text,label,action){$('#confirmTitle').textContent=title;$('#confirmText').textContent=text;$('#confirmOk').textContent=label;confirmAction=action;$('#confirmPanel').classList.remove('hidden')}
function closeConfirm(){$('#confirmPanel').classList.add('hidden');confirmAction=null}
function beginCapture(){show('capture')}
$('#snapStart').onclick=beginCapture;$('#snapAgain').onclick=beginCapture;$('#manualStart').onclick=()=>{clearForm();show('add')};
$$('.sample').forEach(b=>b.onclick=()=>{const s=samples[b.dataset.sample];$('#extractName').value=s.name;$('#extractCategory').value=s.category;$('#extractDate').value=dateAfter(s.days);$('#extractAmount').value=s.amount||'';$('#extractReminder').value='30';$('#extractForm').dataset.sample=b.dataset.sample;show('extract')});
$('#extractForm').onsubmit=e=>{e.preventDefault();const s=samples[e.currentTarget.dataset.sample]||{};items.push({id:uid(),icon:s.icon||'📌',name:$('#extractName').value.trim(),category:$('#extractCategory').value,date:$('#extractDate').value,amount:$('#extractAmount').value,repeat:s.repeat||'none',reminder:$('#extractReminder').value,source:'simulated-scan'});if(save())show('timeline')};
$('#addBtn').onclick=()=>{clearForm();show('add')};$$('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='timeline'&&$('#add').classList.contains('active'))clearForm();show(b.dataset.view)});
$('#itemForm').onsubmit=e=>{e.preventDefault();const id=$('#editId').value;const data={name:$('#name').value.trim(),category:$('#category').value,date:$('#date').value,amount:$('#amount').value,repeat:$('#repeat').value,reminder:$('#reminder').value};if(id){const i=items.findIndex(x=>x.id===id);if(i>=0)items[i]={...items[i],...data}}else items.push({id:uid(),...data});if(save()){clearForm();show('timeline')}};
$('#deleteBtn').onclick=()=>{const id=$('#editId').value;const i=items.find(x=>x.id===id);if(!i)return;openConfirm('Delete tracked item?',`Delete “${i.name}”? This cannot be undone.`,'Delete',()=>{items=items.filter(x=>x.id!==id);save();clearForm();show('timeline')})};
$('#manageBtn').onclick=()=>$('#managePanel').classList.remove('hidden');$('#closeManage').onclick=()=>$('#managePanel').classList.add('hidden');
$('#resetTimeline').onclick=()=>{if(!items.length){$('#managePanel').classList.add('hidden');return}$('#managePanel').classList.add('hidden');openConfirm('Delete all tracked items?',`This will delete all ${items.length} tracked item${items.length===1?'':'s'}. This cannot be undone.`,'Delete all',()=>{items=[];save();show('timeline')})};
$('#resetPrototype').onclick=()=>{$('#managePanel').classList.add('hidden');openConfirm('Reset entire prototype?','This will delete all tracked items and return to the start. This cannot be undone.','Reset prototype',()=>{items=[];try{localStorage.removeItem(KEY)}catch{};show('onboarding')})};
$('#confirmCancel').onclick=closeConfirm;$('#confirmOk').onclick=()=>{const action=confirmAction;closeConfirm();if(action)action()};
if(items.length)show('timeline');