const KEY='mylife-prototype-items';
const templates=[['🚗','Road tax','Vehicle',365,90],['🛡️','Motor insurance / takaful','Insurance',365,1180],['🛜','Internet bill','Bills',30,129],['❄️','Aircond service','Home',180,120],['💧','Water filter','Home',90,80],['💻','Device warranty','Warranty',365,0],['📺','Subscriptions','Subscription',30,55],['🛂','Passport / licence','Personal',730,0]];
let items=[];
try{const stored=JSON.parse(localStorage.getItem(KEY)||'[]');items=Array.isArray(stored)?stored:[]}catch{localStorage.removeItem(KEY)}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function localDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function dateAfter(days){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+days);return localDate(d)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='timeline'||id==='upcoming')render()}
function save(){localStorage.setItem(KEY,JSON.stringify(items))}
function diff(date){const now=new Date();now.setHours(12,0,0,0);return Math.round((new Date(date+'T12:00:00')-now)/86400000)}
function money(n){return 'RM'+Number(n||0).toLocaleString('en-MY',{maximumFractionDigits:2})}
function render(){items.sort((a,b)=>a.date.localeCompare(b.date));const box=$('#items');box.innerHTML=items.length?'':'<div class="empty">Nothing here yet. Add the first thing you never want to forget.</div>';items.forEach(i=>{const d=diff(i.date);box.innerHTML+=`<div class="item"><div class="icon">${i.icon||'📌'}</div><div><strong>${escapeHtml(i.name)}</strong><small>${escapeHtml(i.category)} · ${new Date(i.date+'T12:00:00').toLocaleDateString('en-MY',{day:'numeric',month:'short',year:'numeric'})}${i.amount?' · '+money(i.amount):''}</small></div><div class="days ${d<=14?'urgent':''}">${d<0?'OVERDUE':d===0?'TODAY':d+' DAYS'}</div></div>`});const next=items.filter(i=>{const d=diff(i.date);return d>=0&&d<=90});$('#count').textContent=`${next.length} item${next.length===1?'':'s'}`;$('#cost').textContent=`${money(next.reduce((s,i)=>s+Number(i.amount||0),0))} expected`;const alerts=$('#alerts');const due=items.filter(i=>diff(i.date)<=Number(i.reminder||30));alerts.innerHTML=due.length?'':'<div class="empty">No reminders need your attention.</div>';due.forEach(i=>{const d=diff(i.date);alerts.innerHTML+=`<div class="alert"><strong>${d<0?'⚠️ Overdue':d===0?'🔔 Due today':'🔔 '+d+' days left'} — ${escapeHtml(i.name)}</strong><span>${escapeHtml(i.category)}${i.amount?' · '+money(i.amount):''}</span></div>`})}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
const t=$('#templates');templates.forEach((x,n)=>{const b=document.createElement('button');b.className='chip';b.type='button';b.dataset.i=n;b.innerHTML=`${x[0]} ${x[1]}`;b.onclick=()=>b.classList.toggle('selected');t.appendChild(b)});
$('#start').onclick=()=>{const selected=$$('.chip.selected');if(!selected.length){alert('Choose at least one item to build your first timeline.');return}selected.forEach(b=>{const x=templates[+b.dataset.i];items.push({id:crypto.randomUUID(),icon:x[0],name:x[1],category:x[2],date:dateAfter(x[3]),amount:x[4],repeat:x[3]===30?'monthly':'yearly',reminder:30})});save();show('timeline')};
$('#addBtn').onclick=()=>show('add');$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
$('#itemForm').onsubmit=e=>{e.preventDefault();items.push({id:crypto.randomUUID(),name:$('#name').value.trim(),category:$('#category').value,date:$('#date').value,amount:$('#amount').value,repeat:$('#repeat').value,reminder:$('#reminder').value});save();e.target.reset();show('timeline')};
$('#reset').onclick=()=>{if(confirm('Reset all prototype data?')){items=[];localStorage.removeItem(KEY);$$('.chip').forEach(x=>x.classList.remove('selected'));show('onboarding')}};
if(items.length)show('timeline');
