(()=>{
const RECUR_KEY='mylife-recurring-transactions';
const $=s=>document.querySelector(s);
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function save(v){localStorage.setItem(RECUR_KEY,JSON.stringify(v))}
function money(n){return 'RM'+Number(n||0).toLocaleString('en-MY',{minimumFractionDigits:0,maximumFractionDigits:2})}
function month(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function daysInMonth(){const d=new Date();return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
function transactions(){return load('mylife-money-transactions',[]).filter(x=>String(x.date||'').startsWith(month()))}
function trackedUpcoming(){const now=new Date();now.setHours(12,0,0,0);return load('mylife-prototype-items',[]).filter(i=>{const d=new Date(i.date+'T12:00:00'),delta=Math.round((d-now)/86400000);return delta>=0&&delta<=30}).reduce((s,i)=>s+Number(i.amount||0),0)}
function recurring(){return load(RECUR_KEY,[]).filter(x=>x&&x.id&&x.description&&Number(x.amount)>0&&Number(x.day)>=1&&Number(x.day)<=31)}
function uid(){return globalThis.crypto?.randomUUID?.()||`rec-${Date.now()}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensureUI(){if($('#planningCard'))return;const moneyScreen=$('#money');if(!moneyScreen)return;const txTitle=[...moneyScreen.querySelectorAll('.section-title')].find(x=>x.textContent.includes('Transactions'));const wrap=document.createElement('div');wrap.innerHTML=`<div class="section-title"><div><h2>Cash-flow Forecast</h2><small class="muted">Projects month-end cash using recurring items not yet recorded.</small></div><button id="addRecurring" class="ghost">+ Recurring</button></div><div id="planningCard" class="chart-card"></div><div class="section-title"><div><h2>Financial Alerts</h2><small class="muted">Rule-based planning warnings from current records.</small></div></div><div id="financialAlerts"></div><div class="section-title"><div><h2>Recurring Transactions</h2><small class="muted">Monthly planned income and expenses.</small></div></div><div id="recurringList"></div>`;txTitle?.before(...wrap.children);const modal=document.createElement('div');modal.id='recurringPanel';modal.className='modal hidden';modal.innerHTML=`<div class="modal-card"><h2>Add recurring transaction</h2><form id="recurringForm"><label>Type<select id="recurringType"><option value="expense">Expense</option><option value="income">Income</option></select></label><label>Description<input id="recurringDescription" maxlength="120" required></label><label>Amount (RM)<input id="recurringAmount" type="number" min="0.01" step="0.01" required></label><label>Day of month<input id="recurringDay" type="number" min="1" max="31" required></label><label>Classification<select id="recurringClass"><option>Need</option><option>Want</option><option>Commitment</option></select></label><button class="primary" type="submit">Save recurring item</button><button id="cancelRecurring" class="ghost wide" type="button">Cancel</button></form></div>`;document.body.appendChild(modal);$('#addRecurring').onclick=()=>$('#recurringPanel').classList.remove('hidden');$('#cancelRecurring').onclick=()=>$('#recurringPanel').classList.add('hidden');$('#recurringForm').onsubmit=e=>{e.preventDefault();const list=recurring();list.push({id:uid(),type:$('#recurringType').value,description:$('#recurringDescription').value.trim(),amount:+$('#recurringAmount').value,day:+$('#recurringDay').value,classification:$('#recurringClass').value});save(list);e.target.reset();$('#recurringPanel').classList.add('hidden');render()}}
function matchedPending(rec,tx){const used=new Set();return rec.filter(r=>{const idx=tx.findIndex((x,i)=>!used.has(i)&&x.type===r.type&&String(x.description||'').trim().toLowerCase()===r.description.trim().toLowerCase()&&Math.abs(Number(x.amount)-Number(r.amount))<0.01);if(idx>=0){used.add(idx);return false}return true})}
function render(){ensureUI();if(!$('#planningCard'))return;const tx=transactions(),rec=recurring(),income=tx.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0),spending=tx.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0),saved=tx.filter(x=>x.type==='save').reduce((s,x)=>s+Number(x.amount),0),withdrawn=tx.filter(x=>x.type==='withdraw').reduce((s,x)=>s+Number(x.amount),0),upcoming=trackedUpcoming();const pending=matchedPending(rec,tx),futureIncome=pending.filter(r=>r.type==='income').reduce((s,r)=>s+Number(r.amount),0),futureExpense=pending.filter(r=>r.type==='expense').reduce((s,r)=>s+Number(r.amount),0),currentSafe=income+withdrawn-spending-saved-upcoming,projected=currentSafe+futureIncome-futureExpense;$('#planningCard').innerHTML=`<div class="budget-summary"><span><small>Current safe</small><strong>${money(currentSafe)}</strong></span><span><small>Recurring still unrecorded</small><strong>${money(futureExpense)}</strong></span><span><small>Projected month-end</small><strong>${money(projected)}</strong></span></div><small class="muted">Forecast includes ${money(futureIncome)} recurring income not yet recorded. Past-due recurring items remain in the forecast until matched to an actual transaction.</small>`;const alerts=[];if(projected<0)alerts.push(`Projected month-end deficit: ${money(projected)}.`);if(currentSafe<0)alerts.push(`Current Safe to Spend is negative: ${money(currentSafe)}.`);const budgets=load('mylife-monthly-budgets',{})[month()]||{};['Need','Want','Commitment'].forEach(c=>{const b=Number(budgets[c]||0);if(!b)return;const actual=tx.filter(x=>x.type==='expense'&&x.classification===c).reduce((s,x)=>s+Number(x.amount),0),ratio=actual/b;if(ratio>1)alerts.push(`${c} spending is over budget by ${money(actual-b)}.`);else if(ratio>=.8)alerts.push(`${c} spending has reached ${Math.round(ratio*100)}% of budget.`)});if(!alerts.length)alerts.push('No financial planning alerts from current records.');$('#financialAlerts').innerHTML=alerts.map(a=>`<div class="alert"><strong>${esc(a)}</strong></div>`).join('');const list=$('#recurringList');list.innerHTML=rec.length?'':'<div class="empty compact-empty">No recurring transactions set.</div>';rec.sort((a,b)=>a.day-b.day).forEach(r=>list.innerHTML+=`<div class="ledger"><span><strong>${esc(r.description)}</strong><small>Monthly · day ${Math.min(r.day,daysInMonth())} · ${r.type==='income'?'income':esc(r.classification)}</small></span><b>${r.type==='income'?'+':'−'}${money(r.amount)}</b><button class="ghost delete-recurring" data-id="${esc(r.id)}">Delete</button></div>`);document.querySelectorAll('.delete-recurring').forEach(b=>b.onclick=()=>{save(recurring().filter(r=>r.id!==b.dataset.id));render()})}
ensureUI();render();new MutationObserver(()=>{if($('#money')?.classList.contains('active'))render()}).observe(document.querySelector('.app'),{attributes:true,subtree:true,attributeFilter:['class']});window.addEventListener('storage',render);
})();
