const {test,expect}=require('@playwright/test');
async function openMoney(page){await page.goto('/');const b=page.getByRole('button',{name:'Open Money Overview'});if(await b.isVisible().catch(()=>false))await b.click()}
async function addRecurring(page,type,description,amount,day,classification='Commitment'){await page.locator('#addRecurring').click();await page.locator('#recurringType').selectOption(type);await page.locator('#recurringDescription').fill(description);await page.locator('#recurringAmount').fill(String(amount));await page.locator('#recurringDay').fill(String(day));if(type==='expense')await page.locator('#recurringClass').selectOption(classification);await page.locator('#recurringForm button[type="submit"]').click()}
test.beforeEach(async({page})=>{await page.goto('/');await page.evaluate(()=>localStorage.clear())});
test('PLAN-01 saves recurring transaction',async({page})=>{await openMoney(page);await addRecurring(page,'expense','Internet',129,28);await expect(page.locator('#recurringList')).toContainText('Internet');await expect(page.locator('#recurringList')).toContainText('RM129')});
test('PLAN-02 pending recurring expense reduces forecast only',async({page})=>{await page.goto('/');await page.evaluate(()=>{const d=new Date(),m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;localStorage.setItem('mylife-money-transactions',JSON.stringify([{id:'i',type:'income',description:'Salary',amount:1000,date:`${m}-01`}]))});await openMoney(page);await addRecurring(page,'expense','Future bill',200,31);await expect(page.locator('#safeSpend')).toContainText('RM1,000');await expect(page.locator('#planningCard')).toContainText('RM800')});
test('PLAN-03 matched recorded recurring item is not double counted',async({page})=>{await page.goto('/');await page.evaluate(()=>{const d=new Date(),m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;localStorage.setItem('mylife-money-transactions',JSON.stringify([{id:'i',type:'income',description:'Salary',amount:1000,date:`${m}-01`},{id:'e',type:'expense',description:'Internet',amount:129,date:`${m}-02`,classification:'Commitment'}]))});await openMoney(page);await addRecurring(page,'expense','Internet',129,31);await expect(page.locator('#planningCard')).toContainText('Recurring still unrecordedRM0');await expect(page.locator('#planningCard')).toContainText('Projected month-endRM871')});
test('PLAN-04 negative projection creates alert',async({page})=>{await page.goto('/');await page.evaluate(()=>{const d=new Date(),m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;localStorage.setItem('mylife-money-transactions',JSON.stringify([{id:'i',type:'income',description:'Salary',amount:100,date:`${m}-01`}]))});await openMoney(page);await addRecurring(page,'expense','Large bill',300,31);await expect(page.locator('#financialAlerts')).toContainText('Projected month-end deficit')});
test('PLAN-05 budget near-limit creates alert',async({page})=>{await page.goto('/');await page.evaluate(()=>{const d=new Date(),m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;localStorage.setItem('mylife-money-transactions',JSON.stringify([{id:'e',type:'expense',description:'Food',amount:80,date:`${m}-01`,classification:'Need'}]));localStorage.setItem('mylife-monthly-budgets',JSON.stringify({[m]:{Need:100,Want:0,Commitment:0}}))});await openMoney(page);await expect(page.locator('#financialAlerts')).toContainText('Need spending has reached 80% of budget')});
test('PLAN-06 overdue unrecorded recurring expense remains forecast',async({page})=>{await page.goto('/');await page.evaluate(()=>{const d=new Date(),m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;localStorage.setItem('mylife-money-transactions',JSON.stringify([{id:'i',type:'income',description:'Salary',amount:1000,date:`${m}-01`}]))});await openMoney(page);await addRecurring(page,'expense','Overdue bill',150,1);await expect(page.locator('#planningCard')).toContainText('Recurring still unrecordedRM150');await expect(page.locator('#planningCard')).toContainText('Projected month-endRM850')});
test('PLAN-07 one actual matches only one duplicate recurring item',async({page})=>{await page.goto('/');await page.evaluate(()=>{const d=new Date(),m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;localStorage.setItem('mylife-money-transactions',JSON.stringify([{id:'i',type:'income',description:'Salary',amount:1000,date:`${m}-01`},{id:'e',type:'expense',description:'Fee',amount:100,date:`${m}-02`,classification:'Commitment'}]))});await openMoney(page);await addRecurring(page,'expense','Fee',100,10);await addRecurring(page,'expense','Fee',100,20);await expect(page.locator('#planningCard')).toContainText('Recurring still unrecordedRM100');await expect(page.locator('#planningCard')).toContainText('Projected month-endRM800')});
